ligapokemon_set = (
    ("AQ", "Aquapolis"),
    ("AR", "Arceus"),
    ("B2", "Base Set 2"),
    ("BG", "Best of Game"),
    ("BLW", "Black & White"),
    ("BWPR", "Black & White Promos"),
    ("BWT1", "Black & White Trainer Kit"),
    ("STS", "Cerco de Vapor / Steam Siege"),
    ("ROS", "Céus Estrondosos / Roaring Skies"),
    ("CL", "Chamado das Lendas / Call of Legends"),
    ("DRV", "Cofre do Dragão / Dragon Vault"),
    ("BS", "Coleção Básica / Base Set"),
    ("PRC", "Conflito Primitivo / Primal Clash"),
    ("PLF", "Congelamento de Plasma / Plasma Freeze"),
    ("KSS", "Conjunto para Iniciantes Kalos / Kalos Starter Set"),
    ("DCR", "Crise Dupla / Double Crisis"),
    ("CG", "Crystal Guardians"),
    ("DS", "Delta Species"),
    ("DX", "Deoxys"),
    ("UD", "Destemido / Undaunted"),
    ("DP", "Diamante & Pérola / Diamond & Pearl"),
    ("DPPR", "Diamante & Pérola Promos / Diamond & Pérola Promos"),
    ("DPT1", "Diamond & Pearl Trainer Kit"),
    ("DRX", "Dragões Enaltecidos / Dragons Exalted"),
    ("DGM", "Dragões Soberanos / Dragon Majesty"),
    ("DR", "Dragon"),
    ("DF", "Dragon Frontiers"),
    ("EM", "Emerald"),
    ("EVO", "Evoluções / Evolutions"),
    ("EXT1", "EX Trainer Kit"),
    ("EXT2", "EX Trainer Kit 2"),
    ("EX", "Expedition"),
    ("DEX", "Exploradores da Escuridão / Dark Explorers"),
    ("PLB", "Explosão de Plasma / Plasma Blast"),
    ("RG", "FireRed & LeafGreen"),
    ("FLF", "Flash de Fogo / Flashfire"),
    ("PHF", "Força Fantasma / Phantom Forces"),
    ("FO", "Fóssil / Fossil"),
    ("BCR", "Fronteiras Cruzadas / Boundaries Crossed"),
    ("FCO", "Fusão de Destinos / Fates Collide"),
    ("GEN", "Gerações / Generations"),
    ("GE", "Great Encounters"),
    ("GUR", "Guardiões Ascendentes / Guardians Rising"),
    ("G2", "Gym Challenge"),
    ("G1", "Gym Heroes"),
    ("HS", "HeartGold & SoulSilver"),
    ("HSPR", "HeartGold & SoulSilver Promos"),
    ("HL", "Hidden Legends"),
    ("HP", "Holon Phantoms"),
    ("HST1", "HS Trainer Kit"),
    ("CRI", "Invasão Carmim / Crimson Invasion"),
    ("LM", "Legend Maker"),
    ("LC", "Legendary Collection"),
    ("LA", "Legends Awakened"),
    ("SHL", "Lendas Luminescentes / Shining Legends"),
    ("FLI", "Luz Proibida / Forbidden Light"),
    ("MD", "Majestic Dawn"),
    ("SW", "Maravilhas Secretas / Secret Wonders"),
    ("MCD1", "McDonald’s Collection 2011"),
    ("MCD2", "McDonald’s Collection 2012"),
    ("N4", "Neo Destiny"),
    ("N2", "Neo Discovery"),
    ("N1", "Neo Genesis"),
    ("N3", "Neo Revelation"),
    ("NBSP", "Nintendo Black Star Promos"),
    ("AOR", "Origens Ancestrais / Ancient Origins"),
    ("PL", "Platinum"),
    ("EPO", "Poderes Emergentes / Emerging Powers"),
    ("P1", "POP Series 1"),
    ("P2", "POP Series 2"),
    ("P3", "POP Series 3"),
    ("P4", "POP Series 4"),
    ("P5", "POP Series 5"),
    ("P6", "POP Series 6"),
    ("P7", "POP Series 7"),
    ("P8", "POP Series 8"),
    ("P9", "POP Series 9"),
    ("PK", "Power Keepers"),
    ("PRL", "PreRelease"),
    ("PR", "Promos"),
    ("NXD", "Próximos Destinos / Next Destinies"),
    ("FFI", "Punhos Furiosos / Furious Fists"),
    ("UL", "Revelado / Unleashed"),
    ("RR", "Rising Rivals"),
    ("RS", "Rubi & Safira / Ruby & Sapphire"),
    ("RU", "Rumble"),
    ("SS", "Sandstorm"),
    ("JU", "Selva / Jungle"),
    ("SK", "Skyridge"),
    ("SM", "Sol e Lua / Sun & Moon"),
    ("SMP", "Sol e Lua Promos / Sun & Moon Promos"),
    ("BUS", "Sombras Ardentes / Burning Shadows"),
    ("SI", "Southern Islands"),
    ("SF", "Stormfront"),
    ("SMT1", "Sun & Moon Trainer Kit Lycanroc Raichu"),
    ("SV", "Supreme Victors"),
    ("MA", "Team Magma vs Team Aqua"),
    ("TR", "Team Rocket"),
    ("TRR", "Team Rocket Returns"),
    ("CST", "Tempestade Celestial / Celestial Storm"),
    ("PLS", "Tempestade de Plasma / Plasma Storm"),
    ("LTR", "Tesouros Lendários / Legendary Treasures"),
    ("MT", "Tesouros Misteriosos / Mysterious Treasures"),
    ("TM", "Triunfante / Triumphant"),
    ("LOT", "Trovões Perdidos / Lost Thunder"),
    ("BKP", "Turbo Colisão / BREAKpoint"),
    ("BKT", "Turbo Revolução / BREAKthrough"),
    ("ULP", "Ultraprisma / Ultra Prism"),
    ("UF", "Unseen Forces"),
    ("VM", "Victory Medals"),
    ("NVI", "Vitórias Nobres / Noble Victories"),
    ("WPR", "Wizards Black Star Promos"),
    ("WC", "World Collection"),
    ("XY", "XY"),
    ("XYPR", "XY Promos"),
    ("XYT3", "XY Trainer Kit"),
    ("XYT4", "XY Trainer Kit: Bisharp and Wigglytuff"),
    ("XYT1", "XY Trainer Kit: Latias and Latios"),
    ("XYT2", "XY Trainer Kit: Pikachu Libre and Suicune"),
)
