ligapokemon_set = (
    ("AQ", "Aquapolis"),
    ("AR", "Arceus"),
    ("B2", "Base Set 2"),
    ("BG", "Best of Game"),
    ("BLW", "Black & White"),
    ("BWPR", "Black & White Promos"),
    ("BWT1", "Black & White Trainer Kit"),
    ("TK5B", "Black & White Trainer Kit—Excadrill"),
    ("TK5A", "Black & White Trainer Kit—Zoroark"),
    ("BTP", "Box Topper"),
    ("STS", "Cerco de Vapor / Steam Siege"),
    ("ROS", "Céus Estrondosos / Roaring Skies"),
    ("CL", "Chamado das Lendas / Call of Legends"),
    ("DRV", "Cofre do Dragão / Dragon Vault"),
    ("BS", "Coleção Básica / Base Set"),
    ("PRC", "Conflito Primitivo / Primal Clash"),
    ("PLF", "Congelamento de Plasma / Plasma Freeze"),
    ("KSS", "Conjunto para Iniciantes Kalos / Kalos Starter Set"),
    ("DCR", "Crise Dupla / Double Crisis"),
    ("CG", "Crystal Guardians"),
    ("DS", "Delta Species"),
    ("DX", "Deoxys"),
    ("UD", "Destemido / Undaunted"),
    ("HDF", "Destinos Ocultos / Hidden Fates"),
    ("DET", "Detective Pikachu"),
    ("DP", "Diamante & Pérola / Diamond & Pearl"),
    ("DPPR", "Diamante & Pérola Promos / Diamond & Pearl Promos"),
    ("DPT1", "Diamond & Pearl Trainer Kit"),
    ("TK3B", "Diamond & Pearl Trainer Kit—Lucario"),
    ("TK3A", "Diamond & Pearl Trainer Kit—Manaphy"),
    ("DRX", "Dragões Enaltecidos / Dragons Exalted"),
    ("DGM", "Dragões Soberanos / Dragon Majesty"),
    ("DR", "Dragon"),
    ("DF", "Dragon Frontiers"),
    ("CEC", "Eclipse Cósmico / Cosmic Eclipse"),
    ("UBB", "Elos Inquebráveis / Unbroken Bonds"),
    ("EM", "Emerald"),
    ("DAB", "Escuridão Incandescente / Darkness Ablaze"),
    ("EVO", "Evoluções / Evolutions"),
    ("EXT1", "EX Trainer Kit"),
    ("EXT2", "EX Trainer Kit 2"),
    ("TK1A", "EX Trainer Kit—Latias"),
    ("TK1B", "EX Trainer Kit—Latios"),
    ("TK2M", "EX Trainer Kit—Minun"),
    ("TK2P", "EX Trainer Kit—Plusle"),
    ("EX", "Expedition"),
    ("DEX", "Exploradores da Escuridão / Dark Explorers"),
    ("PLB", "Explosão de Plasma / Plasma Blast"),
    ("RG", "FireRed & LeafGreen"),
    ("FLF", "Flash de Fogo / Flashfire"),
    ("PHF", "Força Fantasma / Phantom Forces"),
    ("FO", "Fóssil / Fossil"),
    ("BCR", "Fronteiras Cruzadas / Boundaries Crossed"),
    ("FCO", "Fusão de Destinos / Fates Collide"),
    ("GEN", "Gerações / Generations"),
    ("GE", "Great Encounters"),
    ("GUR", "Guardiões Ascendentes / Guardians Rising"),
    ("G2", "Gym Challenge"),
    ("G1", "Gym Heroes"),
    ("HS", "HeartGold & SoulSilver"),
    ("HSPR", "HeartGold & SoulSilver Promos"),
    ("HL", "Hidden Legends"),
    ("HP", "Holon Phantoms"),
    ("HST1", "HS Trainer Kit"),
    ("TK4G", "HS Trainer Kit—Gyarados"),
    ("TK4R", "HS Trainer Kit—Raichu"),
    ("CRI", "Invasão Carmim / Crimson Invasion"),
    ("JPR", "Japanese Promos"),
    ("LM", "Legend Maker"),
    ("LC", "Legendary Collection"),
    ("LA", "Legends Awakened"),
    ("SHL", "Lendas Luminescentes / Shining Legends"),
    ("FLI", "Luz Proibida / Forbidden Light"),
    ("MD", "Majestic Dawn"),
    ("SW", "Maravilhas Secretas / Secret Wonders"),
    ("MCD1", "McDonald’s Collection 2011"),
    ("MCD2", "McDonald’s Collection 2012"),
    ("MCD16", "McDonald’s Collection 2016"),
    ("MCD19", "McDonald’s Collection 2019"),
    ("MCD", "McDonald's Collection 2011"),
    ("MCD", "McDonald's Collection 2012"),
    ("N4", "Neo Destiny"),
    ("N2", "Neo Discovery"),
    ("N1", "Neo Genesis"),
    ("N3", "Neo Revelation"),
    ("NBSP", "Nintendo Black Star Promos"),
    ("AOR", "Origens Ancestrais / Ancient Origins"),
    ("PL", "Platinum"),
    ("EPO", "Poderes Emergentes / Emerging Powers"),
    ("P1", "POP Series 1"),
    ("P2", "POP Series 2"),
    ("P3", "POP Series 3"),
    ("P4", "POP Series 4"),
    ("P5", "POP Series 5"),
    ("P6", "POP Series 6"),
    ("P7", "POP Series 7"),
    ("P8", "POP Series 8"),
    ("P9", "POP Series 9"),
    ("PK", "Power Keepers"),
    ("PRL", "PreRelease"),
    ("PR", "Promos"),
    ("NXD", "Próximos Destinos / Next Destinies"),
    ("FFI", "Punhos Furiosos / Furious Fists"),
    ("UL", "Revelado / Unleashed"),
    ("RR", "Rising Rivals"),
    ("RBC", "Rixa Rebelde / Rebel Clash"),
    ("RS", "Rubi & Safira / Ruby & Sapphire"),
    ("RU", "Rumble"),
    ("SS", "Sandstorm"),
    ("JU", "Selva / Jungle"),
    ("UNM", "Sintonia Mental / Unified Minds"),
    ("SK", "Skyridge"),
    ("SM", "Sol e Lua / Sun & Moon"),
    ("SMP", "Sol e Lua Promos / Sun & Moon Promos"),
    ("BUS", "Sombras Ardentes / Burning Shadows"),
    ("SI", "Southern Islands"),
    ("SF", "Stormfront"),
    ("SMT1", "Sun & Moon Trainer Kit Lycanroc and Alolan Raichu"),
    ("TK10B", "Sun & Moon Trainer Kit—Alolan Raichu"),
    ("TK10A", "Sun & Moon Trainer Kit—Lycanroc"),
    ("SV", "Supreme Victors"),
    ("SAS", "Sword & Shield"),
    ("SSP", "Sword & Shield Promos"),
    ("MA", "Team Magma vs Team Aqua"),
    ("TR", "Team Rocket"),
    ("TRR", "Team Rocket Returns"),
    ("CST", "Tempestade Celestial / Celestial Storm"),
    ("PLS", "Tempestade de Plasma / Plasma Storm"),
    ("LTR", "Tesouros Lendários / Legendary Treasures"),
    ("MT", "Tesouros Misteriosos / Mysterious Treasures"),
    ("TM", "Triunfante / Triumphant"),
    ("LOT", "Trovões Perdidos / Lost Thunder"),
    ("BKP", "Turbo Colisão / BREAKpoint"),
    ("BKT", "Turbo Revolução / BREAKthrough"),
    ("ULP", "Ultraprisma / Ultra Prism"),
    ("TUP", "União de Aliados / Team Up"),
    ("UF", "Unseen Forces"),
    ("VM", "Victory Medals"),
    ("NVI", "Vitórias Nobres / Noble Victories"),
    ("WPR", "Wizards Black Star Promos"),
    ("WC", "World Collection"),
    ("XY", "XY"),
    ("XYPR", "XY Promos"),
    ("XYT3", "XY Trainer Kit"),
    ("XYT4", "XY Trainer Kit: Bisharp and Wigglytuff"),
    ("XYT1", "XY Trainer Kit: Latias and Latios"),
    ("XYT2", "XY Trainer Kit: Pikachu Libre and Suicune"),
    ("TK8B", "XY Trainer Kit—Latias"),
    ("TK8A", "XY Trainer Kit—Latios"),
    ("TK6A", "XY Trainer Kit—Noivern"),
    ("TK9A", "XY Trainer Kit—Pikachu Libre"),
    ("TK9B", "XY Trainer Kit—Suicune"),
    ("TK6B", "XY Trainer Kit—Sylveon"),
)
